messages:
    responses:
      start: "Привет! Это бот \"Письма в будущее\". Чтобы ознакомиться поподробнее с тем, что я умею, вызовете комманду /help."
      help_text: "Я отправляю письма в будущее. Как это работает? Ты присылаешь мне письмо, которое хочешь получить на какую-то конкретную дату в будущем. Затем, тебе будет дана возможность указать свою почту, на которую ты желаешь получить то самое послание. Имей в виду, что после процесса отправки своего письма, я его удалю из чата, для того, чтобы сохранить интригу и дать твоему мозгу возможность забыть о нем! Ты оставляешь сто рублей в зимней куртке и благополучно забываешь о них, а через сезон надеваешь ее и \"ого, ничего себе\" - ты нащупываешь те самые рубли и радуешься! Здесь принцип схожий) P.S: Дата должна быть в формате \"год-месяц-день\" и не может выходить за рамки определенного мной периода: настоящее время - 2024-03-30 Для того чтобы начать вызовете команду /goletter. Кроме того, если по какой-то причине на одном из этапов отправки письма вы передумали отправлять его, нажмите /stop."
      goletter: "Отправьте текст своего письма:"
      email: "Теперь введите вашу почту:"
      date: "Отлично, теперь введите дату:"
      result: "Спасибо! Ваше письмо, почта и дата будут удалены из чата через пару секунд! Имейте в виду, что ,возможно, ваше послание может попасть в спам, поэтому, во избежании данного недоразумения, рекомендуется добавить следующую почту в избранное в вашем почтовом ящике - lettertofuturebot@gmail.com. Если вы хотите отправить еще одно письмо в будущее, нажмите /goletter. Удачи!"
    errors:
      start_true: "Нажмите /help"
      help_true: "Нажмите /goletter"
      size_letter: "Извини, я не могу сохранить такое большое письмо. Сократите его и попробуйте еще раз!"
      invalid_email: "Проверьте правильность введенной почты!"
      invalid_date: "Проверьте правильность введенной даты! Дата должна быть в формате yyyy-mm-dd. Кроме того, проверьте еще раз точность введенной вами даты! Я могу сохранять ваши письма только от актуальной даты до 2025-03-28"




